[package]
name = "saeos"
version = "0.1.0"
edition.workspace = true

[dependencies]

[features]
default = []
serial = []
framebuffer = []
vga-text = []
keyboard = []
mm-selftest = []
paging-debug = []
mm-stress = []
mm-lock-debug = []
mm-allocator-stats = []
apic = []
pit = []
rtc = []
apic-timer = ["apic"]
tsc = []
scheduler-selftest = []
scheduler-debug = []

[[bin]]
name = "saeos"
test = false
bench = false
