[module]
id = "kernel"
name = "Kernel"

[config]
files = []
children = [
    "src/scheduler/SConfig.toml",
    "src/time/SConfig.toml",
    "src/mm/SConfig.toml",
    "src/drivers/SConfig.toml",
    "src/arch/x86_64/SConfig.toml",
]
