[kernel.time]
pit = false
rtc = false
apic_timer = false
tsc = false

[kernel.mm]
selftest = false
paging_debug = false
stress = false
lock_debug = false
allocator_stats = false

[kernel.drivers]
serial = true
framebuffer = false
vga_text = true
keyboard = false

[kernel.arch.x86_64]
apic = false
